// FILE: src/constants/ui.ts
// Hourly Conditions Component
export const HOURLY_CONDITIONS_POINT_ITEM_WIDTH = 60;
export const HOURLY_CONDITIONS_CHART_HEIGHT = 60;
export const HOURLY_CONDITIONS_VALUES_ROW_HEIGHT = 28;
export const HOURLY_CONDITIONS_DETAILS_ROW_HEIGHT = 55;
export const HOURLY_CONDITIONS_CARD_PADDING_HORIZONTAL = 16;

// Snackbar
export const SNACKBAR_DURATION_LONG = 3000;
